version: '3'

services:
  server:
    build: ./everempire-server
    image: ${IMAGE_PREFIX}everempire-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${CERT_PATH}:/certs

  webapp:
    build: ../everempire-webapp
    image: ${IMAGE_PREFIX}everempire-webapp
#    ports:
#      - 8080:80
    env_file:
      - env/webapp.env

  api:
    build: ../everempire-api
    image: ${IMAGE_PREFIX}everempire-api
#    ports:
#      - 9292:9292
    env_file:
      - env/api.env

  genesis:
    build: ../everempire-genesis
    image: ${IMAGE_PREFIX}everempire-genesis
    ports:
      - 1127:1127
    volumes:
      - ${CERT_PATH}:/certs
    env_file:
      - env/genesis.env

  db:
    build: ./everempire-db
    image: ${IMAGE_PREFIX}everempire-db
#    ports:
#      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
